### ISSUE TITLE
Review measures for sub-control dependencies

### ISSUE THREAD

**Issue by adammontville** [adammontville/cis-controls-71-measures#180]
**Need to add dependencies to our metrics.** Whenever we refer to assuming another sub-control is met, that should be a dependent measure effecting the outcome of the current measure. For example, 5.3 depends on 5.4, and if 5.4 fails, then 5.3 should be effected (at least a partial fail).

**Comment by wmunyan** [comment]
TODO:  Add "Dependencies" section to RtDs template and update existing metrics to reflect any dependencies found during this review.

**Comment by adammontville** [comment]
Review each sub-control for presence of Dependencies section.

**Comment by wmunyan** [comment]
Done
