### ISSUE TITLE
Consider identifying all input variables for global reuse

### ISSUE THREAD

**Issue by adammontville** [adammontville/cis-controls-71-measures#181]
As an example, several sub-control measures require the list of endpoints as an input. If that were identified, then it could be reused by implementations, and could be valuable if we ever get around to creating a CAS information/data model.

**Comment by wmunyan** [comment]
Update the "terminology.md" file with necessary items

**Comment by adammontville** [comment]
Go through and expand acronyms. Create an issue to review measures for proper terms post-release.

**Comment by adammontville** [comment]
Done.
