### ISSUE TITLE
Define GH branching strategy for releases

### ISSUE THREAD

**Issue by adammontville** [adammontville/cis-controls-71-measures#193]
Want "latest" render in RtD to reflect the latest _official_ release.
Want RtD to also render work in progress
Want RtD to also render previously releases

Define the branching strategy and whatever process/procedure (minimal) may be necessary.

**Comment by wmunyan** [comment]
Release Procedures: https://sbpaatlassian.cisecurity.org:8090/display/PROD/CAS+Release+Procedures

With release procedures like this, the "latest" render is the most up to date development branch, and the "stable" render is the latest tagged release.

RtD versioning allows for the activation/deactivation of previous release tags so prior releases can still be viewed.

No real branching strategy is needed using this release methodology.  Closing.
